####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-common
Description: Open Porous Media Initiative shared infrastructure
Version: 2025.10-pre
Label: 2025.10-pre
Maintainer: opm@opm-project.org
MaintainerName: OPM community
Url: http://opm-project.org
Depends: dune-common (>= 2.9)
