.TH SUMMARY "1" "October 2024" "arraylist 2024.10" "User Commands"
.SH NAME
arraylist \- Printer for list of arrays in Eclipse summary files
.SH SYNOPSIS
.B arraylist
[\fI\,OPTIONS\/\fR] \fI\,ECL_DECK_FILENAME\/\fR
.SH DESCRIPTION
List all arrays found in an EclFile specified on the command line.
.PP
.SH OPTIONS
\fB\-h\fR Print help and exit.
.TP
\fB\-r\fR List array for a specific report time step number. Option only valid for a unified restart file.
.PP
