.TH SUMMARY "1" "October 2024" "summary" "User Commands"
.SH NAME
summary \- Printer for summary keys in Eclipse summary files
.SH SYNOPSIS
.B summary
[\fI\,OPTIONS\/\fR] \fI\,ECL_DECK_FILENAME\/\fR
\fI\,SUMMARY_KEY1\/\fR [\fI\,SUMMARY_KEY2\/\fR] ...
.SH DESCRIPTION
summary needs a minimum of two arguments. First is smspec filename and
then list of vectors to print.
.SH OPTIONS
.PP
In addition, the program takes these options (which must be given before the arguments):
.PP
.SH OPTIONS
\fB\-h\fR Print help and exit.
.TP
\fB\-l\fR list all summary vectors.
.TP
\fB\-r\fR extract data only for report steps.
.PP
