import datetime
import numpy
from typing import ClassVar, Dict, Iterator, List, Tuple, overload

C0nn: eclArrType
CHAR: eclArrType
DOUB: eclArrType
EDIT: eclSectionType
GRID: eclSectionType
INTE: eclArrType
LOGI: eclArrType
MESS: eclArrType
PROPS: eclSectionType
REAL: eclArrType
REGIONS: eclSectionType
RUNSPEC: eclSectionType
SCHEDULE: eclSectionType
SOLUTION: eclSectionType
SUMMARY: eclSectionType
current_ecl_state: EclipseState
current_report_step: int
current_schedule: Schedule
current_summary_state: SummaryState
class Builtin:
    def __init__(self) -> None: ...
    def __getitem__(self, arg0: str) -> ParserKeyword: ...
    @property
    def ACF(self) -> ParserKeyword: ...
    @property
    def ACTCO2S(self) -> ParserKeyword: ...
    @property
    def ACTDIMS(self) -> ParserKeyword: ...
    @property
    def ACTION(self) -> ParserKeyword: ...
    @property
    def ACTIONG(self) -> ParserKeyword: ...
    @property
    def ACTIONR(self) -> ParserKeyword: ...
    @property
    def ACTIONS(self) -> ParserKeyword: ...
    @property
    def ACTIONW(self) -> ParserKeyword: ...
    @property
    def ACTIONX(self) -> ParserKeyword: ...
    @property
    def ACTNUM(self) -> ParserKeyword: ...
    @property
    def ACTPARAM(self) -> ParserKeyword: ...
    @property
    def ADD(self) -> ParserKeyword: ...
    @property
    def ADDREG(self) -> ParserKeyword: ...
    @property
    def ADDZCORN(self) -> ParserKeyword: ...
    @property
    def ADSALNOD(self) -> ParserKeyword: ...
    @property
    def ADSORP(self) -> ParserKeyword: ...
    @property
    def AITS(self) -> ParserKeyword: ...
    @property
    def AITSOFF(self) -> ParserKeyword: ...
    @property
    def ALKADS(self) -> ParserKeyword: ...
    @property
    def ALKALINE(self) -> ParserKeyword: ...
    @property
    def ALKROCK(self) -> ParserKeyword: ...
    @property
    def ALL(self) -> ParserKeyword: ...
    @property
    def ALPOLADS(self) -> ParserKeyword: ...
    @property
    def ALSURFAD(self) -> ParserKeyword: ...
    @property
    def ALSURFST(self) -> ParserKeyword: ...
    @property
    def AMALGAM(self) -> ParserKeyword: ...
    @property
    def API(self) -> ParserKeyword: ...
    @property
    def APIGROUP(self) -> ParserKeyword: ...
    @property
    def APILIM(self) -> ParserKeyword: ...
    @property
    def APIVD(self) -> ParserKeyword: ...
    @property
    def AQANCONL(self) -> ParserKeyword: ...
    @property
    def AQANNC(self) -> ParserKeyword: ...
    @property
    def AQANTRC(self) -> ParserKeyword: ...
    @property
    def AQUALIST(self) -> ParserKeyword: ...
    @property
    def AQUANCON(self) -> ParserKeyword: ...
    @property
    def AQUCHGAS(self) -> ParserKeyword: ...
    @property
    def AQUCHWAT(self) -> ParserKeyword: ...
    @property
    def AQUCON(self) -> ParserKeyword: ...
    @property
    def AQUCT(self) -> ParserKeyword: ...
    @property
    def AQUCWFAC(self) -> ParserKeyword: ...
    @property
    def AQUDIMS(self) -> ParserKeyword: ...
    @property
    def AQUFET(self) -> ParserKeyword: ...
    @property
    def AQUFETP(self) -> ParserKeyword: ...
    @property
    def AQUFLUX(self) -> ParserKeyword: ...
    @property
    def AQUIFER_PROBE_ANALYTIC(self) -> ParserKeyword: ...
    @property
    def AQUIFER_PROBE_ANALYTIC_NAMED(self) -> ParserKeyword: ...
    @property
    def AQUIFER_PROBE_NUMERIC(self) -> ParserKeyword: ...
    @property
    def AQUNNC(self) -> ParserKeyword: ...
    @property
    def AQUNUM(self) -> ParserKeyword: ...
    @property
    def AQUTAB(self) -> ParserKeyword: ...
    @property
    def AUTOCOAR(self) -> ParserKeyword: ...
    @property
    def AUTOREF(self) -> ParserKeyword: ...
    @property
    def BC(self) -> ParserKeyword: ...
    @property
    def BCCON(self) -> ParserKeyword: ...
    @property
    def BCPROP(self) -> ParserKeyword: ...
    @property
    def BDENSITY(self) -> ParserKeyword: ...
    @property
    def BGGI(self) -> ParserKeyword: ...
    @property
    def BIC(self) -> ParserKeyword: ...
    @property
    def BIGMODEL(self) -> ParserKeyword: ...
    @property
    def BIOTCOEF(self) -> ParserKeyword: ...
    @property
    def BLACKOIL(self) -> ParserKeyword: ...
    @property
    def BLOCK_PROBE(self) -> ParserKeyword: ...
    @property
    def BLOCK_PROBE300(self) -> ParserKeyword: ...
    @property
    def BOGI(self) -> ParserKeyword: ...
    @property
    def BOUNDARY(self) -> ParserKeyword: ...
    @property
    def BOX(self) -> ParserKeyword: ...
    @property
    def BPARA(self) -> ParserKeyword: ...
    @property
    def BPIDIMS(self) -> ParserKeyword: ...
    @property
    def BRANPROP(self) -> ParserKeyword: ...
    @property
    def BRINE(self) -> ParserKeyword: ...
    @property
    def BTOBALFA(self) -> ParserKeyword: ...
    @property
    def BTOBALFV(self) -> ParserKeyword: ...
    @property
    def CALTRAC(self) -> ParserKeyword: ...
    @property
    def CARFIN(self) -> ParserKeyword: ...
    @property
    def CART(self) -> ParserKeyword: ...
    @property
    def CBMOPTS(self) -> ParserKeyword: ...
    @property
    def CECON(self) -> ParserKeyword: ...
    @property
    def CECONT(self) -> ParserKeyword: ...
    @property
    def CIRCLE(self) -> ParserKeyword: ...
    @property
    def CNAMES(self) -> ParserKeyword: ...
    @property
    def CO2SOL(self) -> ParserKeyword: ...
    @property
    def CO2STOR(self) -> ParserKeyword: ...
    @property
    def CO2STORE(self) -> ParserKeyword: ...
    @property
    def COAL(self) -> ParserKeyword: ...
    @property
    def COALADS(self) -> ParserKeyword: ...
    @property
    def COALNUM(self) -> ParserKeyword: ...
    @property
    def COALPP(self) -> ParserKeyword: ...
    @property
    def COARSEN(self) -> ParserKeyword: ...
    @property
    def COLLAPSE(self) -> ParserKeyword: ...
    @property
    def COLUMNS(self) -> ParserKeyword: ...
    @property
    def COMPDAT(self) -> ParserKeyword: ...
    @property
    def COMPDATX(self) -> ParserKeyword: ...
    @property
    def COMPFLSH(self) -> ParserKeyword: ...
    @property
    def COMPIMB(self) -> ParserKeyword: ...
    @property
    def COMPINJK(self) -> ParserKeyword: ...
    @property
    def COMPLMPL(self) -> ParserKeyword: ...
    @property
    def COMPLUMP(self) -> ParserKeyword: ...
    @property
    def COMPOFF(self) -> ParserKeyword: ...
    @property
    def COMPORD(self) -> ParserKeyword: ...
    @property
    def COMPRIV(self) -> ParserKeyword: ...
    @property
    def COMPRP(self) -> ParserKeyword: ...
    @property
    def COMPRPL(self) -> ParserKeyword: ...
    @property
    def COMPS(self) -> ParserKeyword: ...
    @property
    def COMPSEGL(self) -> ParserKeyword: ...
    @property
    def COMPSEGS(self) -> ParserKeyword: ...
    @property
    def COMPTRAJ(self) -> ParserKeyword: ...
    @property
    def COMPVE(self) -> ParserKeyword: ...
    @property
    def COMPVEL(self) -> ParserKeyword: ...
    @property
    def CONNECTION_PROBE(self) -> ParserKeyword: ...
    @property
    def CONNECTION_PROBE_OPM(self) -> ParserKeyword: ...
    @property
    def COORD(self) -> ParserKeyword: ...
    @property
    def COORDSYS(self) -> ParserKeyword: ...
    @property
    def COPY(self) -> ParserKeyword: ...
    @property
    def COPYBOX(self) -> ParserKeyword: ...
    @property
    def COPYREG(self) -> ParserKeyword: ...
    @property
    def CPIFACT(self) -> ParserKeyword: ...
    @property
    def CPIFACTL(self) -> ParserKeyword: ...
    @property
    def CPR(self) -> ParserKeyword: ...
    @property
    def CREF(self) -> ParserKeyword: ...
    @property
    def CREFW(self) -> ParserKeyword: ...
    @property
    def CREFWS(self) -> ParserKeyword: ...
    @property
    def CRITPERM(self) -> ParserKeyword: ...
    @property
    def CSKIN(self) -> ParserKeyword: ...
    @property
    def DATE(self) -> ParserKeyword: ...
    @property
    def DATES(self) -> ParserKeyword: ...
    @property
    def DATUM(self) -> ParserKeyword: ...
    @property
    def DATUMR(self) -> ParserKeyword: ...
    @property
    def DATUMRX(self) -> ParserKeyword: ...
    @property
    def DCQDEFN(self) -> ParserKeyword: ...
    @property
    def DEBUG_(self) -> ParserKeyword: ...
    @property
    def DELAYACT(self) -> ParserKeyword: ...
    @property
    def DENSITY(self) -> ParserKeyword: ...
    @property
    def DEPTH(self) -> ParserKeyword: ...
    @property
    def DEPTHTAB(self) -> ParserKeyword: ...
    @property
    def DEPTHZ(self) -> ParserKeyword: ...
    @property
    def DIAGDISP(self) -> ParserKeyword: ...
    @property
    def DIFF(self) -> ParserKeyword: ...
    @property
    def DIFFAGAS(self) -> ParserKeyword: ...
    @property
    def DIFFAWAT(self) -> ParserKeyword: ...
    @property
    def DIFFC(self) -> ParserKeyword: ...
    @property
    def DIFFCGAS(self) -> ParserKeyword: ...
    @property
    def DIFFCOAL(self) -> ParserKeyword: ...
    @property
    def DIFFCWAT(self) -> ParserKeyword: ...
    @property
    def DIFFDP(self) -> ParserKeyword: ...
    @property
    def DIFFMMF(self) -> ParserKeyword: ...
    @property
    def DIFFMR(self) -> ParserKeyword: ...
    @property
    def DIFFMTHT(self) -> ParserKeyword: ...
    @property
    def DIFFMX(self) -> ParserKeyword: ...
    @property
    def DIFFMY(self) -> ParserKeyword: ...
    @property
    def DIFFMZ(self) -> ParserKeyword: ...
    @property
    def DIFFR(self) -> ParserKeyword: ...
    @property
    def DIFFTHT(self) -> ParserKeyword: ...
    @property
    def DIFFUSE(self) -> ParserKeyword: ...
    @property
    def DIFFX(self) -> ParserKeyword: ...
    @property
    def DIFFY(self) -> ParserKeyword: ...
    @property
    def DIFFZ(self) -> ParserKeyword: ...
    @property
    def DIMENS(self) -> ParserKeyword: ...
    @property
    def DIMPES(self) -> ParserKeyword: ...
    @property
    def DIMPLICT(self) -> ParserKeyword: ...
    @property
    def DISGAS(self) -> ParserKeyword: ...
    @property
    def DISGASW(self) -> ParserKeyword: ...
    @property
    def DISPDIMS(self) -> ParserKeyword: ...
    @property
    def DISPERC(self) -> ParserKeyword: ...
    @property
    def DISPERSE(self) -> ParserKeyword: ...
    @property
    def DOMAINS(self) -> ParserKeyword: ...
    @property
    def DPGRID(self) -> ParserKeyword: ...
    @property
    def DPKRMOD(self) -> ParserKeyword: ...
    @property
    def DPNUM(self) -> ParserKeyword: ...
    @property
    def DR(self) -> ParserKeyword: ...
    @property
    def DREF(self) -> ParserKeyword: ...
    @property
    def DREFS(self) -> ParserKeyword: ...
    @property
    def DRILPRI(self) -> ParserKeyword: ...
    @property
    def DRSDT(self) -> ParserKeyword: ...
    @property
    def DRSDTCON(self) -> ParserKeyword: ...
    @property
    def DRSDTR(self) -> ParserKeyword: ...
    @property
    def DRV(self) -> ParserKeyword: ...
    @property
    def DRVDT(self) -> ParserKeyword: ...
    @property
    def DRVDTR(self) -> ParserKeyword: ...
    @property
    def DSPDEINT(self) -> ParserKeyword: ...
    @property
    def DTHETA(self) -> ParserKeyword: ...
    @property
    def DTHETAV(self) -> ParserKeyword: ...
    @property
    def DUALPERM(self) -> ParserKeyword: ...
    @property
    def DUALPORO(self) -> ParserKeyword: ...
    @property
    def DUMPCUPL(self) -> ParserKeyword: ...
    @property
    def DUMPFLUX(self) -> ParserKeyword: ...
    @property
    def DX(self) -> ParserKeyword: ...
    @property
    def DXV(self) -> ParserKeyword: ...
    @property
    def DY(self) -> ParserKeyword: ...
    @property
    def DYNAMICR(self) -> ParserKeyword: ...
    @property
    def DYNRDIMS(self) -> ParserKeyword: ...
    @property
    def DYV(self) -> ParserKeyword: ...
    @property
    def DZ(self) -> ParserKeyword: ...
    @property
    def DZMATRIX(self) -> ParserKeyword: ...
    @property
    def DZMTRX(self) -> ParserKeyword: ...
    @property
    def DZMTRXV(self) -> ParserKeyword: ...
    @property
    def DZNET(self) -> ParserKeyword: ...
    @property
    def DZV(self) -> ParserKeyword: ...
    @property
    def ECHO(self) -> ParserKeyword: ...
    @property
    def ECLMC(self) -> ParserKeyword: ...
    @property
    def EDIT(self) -> ParserKeyword: ...
    @property
    def EDITNNC(self) -> ParserKeyword: ...
    @property
    def EDITNNCR(self) -> ParserKeyword: ...
    @property
    def EHYSTR(self) -> ParserKeyword: ...
    @property
    def EHYSTRR(self) -> ParserKeyword: ...
    @property
    def END(self) -> ParserKeyword: ...
    @property
    def ENDACTIO(self) -> ParserKeyword: ...
    @property
    def ENDBOX(self) -> ParserKeyword: ...
    @property
    def ENDDYN(self) -> ParserKeyword: ...
    @property
    def ENDFIN(self) -> ParserKeyword: ...
    @property
    def ENDINC(self) -> ParserKeyword: ...
    @property
    def ENDNUM(self) -> ParserKeyword: ...
    @property
    def ENDPOINT_SPECIFIERS(self) -> ParserKeyword: ...
    @property
    def ENDSCALE(self) -> ParserKeyword: ...
    @property
    def ENDSKIP(self) -> ParserKeyword: ...
    @property
    def ENKRVD(self) -> ParserKeyword: ...
    @property
    def ENPCVD(self) -> ParserKeyword: ...
    @property
    def ENPTVD(self) -> ParserKeyword: ...
    @property
    def ENSPCVD(self) -> ParserKeyword: ...
    @property
    def EOS(self) -> ParserKeyword: ...
    @property
    def EOSNUM(self) -> ParserKeyword: ...
    @property
    def EPSDBGS(self) -> ParserKeyword: ...
    @property
    def EPSDEBUG(self) -> ParserKeyword: ...
    @property
    def EQLDIMS(self) -> ParserKeyword: ...
    @property
    def EQLNUM(self) -> ParserKeyword: ...
    @property
    def EQLOPTS(self) -> ParserKeyword: ...
    @property
    def EQLZCORN(self) -> ParserKeyword: ...
    @property
    def EQUALREG(self) -> ParserKeyword: ...
    @property
    def EQUALS(self) -> ParserKeyword: ...
    @property
    def EQUIL(self) -> ParserKeyword: ...
    @property
    def ESSNODE(self) -> ParserKeyword: ...
    @property
    def EXCAVATE(self) -> ParserKeyword: ...
    @property
    def EXCEL(self) -> ParserKeyword: ...
    @property
    def EXIT(self) -> ParserKeyword: ...
    @property
    def EXTFIN(self) -> ParserKeyword: ...
    @property
    def EXTHOST(self) -> ParserKeyword: ...
    @property
    def EXTRAPMS(self) -> ParserKeyword: ...
    @property
    def EXTREPGL(self) -> ParserKeyword: ...
    @property
    def FAULTDIM(self) -> ParserKeyword: ...
    @property
    def FAULTS(self) -> ParserKeyword: ...
    @property
    def FBHPDEF(self) -> ParserKeyword: ...
    @property
    def FHERCHBL(self) -> ParserKeyword: ...
    @property
    def FIELD(self) -> ParserKeyword: ...
    @property
    def FIELDSEP(self) -> ParserKeyword: ...
    @property
    def FIELD_PROBE(self) -> ParserKeyword: ...
    @property
    def FIELD_PROBE_OPM(self) -> ParserKeyword: ...
    @property
    def FILEUNIT(self) -> ParserKeyword: ...
    @property
    def FILLEPS(self) -> ParserKeyword: ...
    @property
    def FIPNUM(self) -> ParserKeyword: ...
    @property
    def FIPOWG(self) -> ParserKeyword: ...
    @property
    def FIPSEP(self) -> ParserKeyword: ...
    @property
    def FIP_PROBE(self) -> ParserKeyword: ...
    @property
    def FLUXNUM(self) -> ParserKeyword: ...
    @property
    def FLUXREG(self) -> ParserKeyword: ...
    @property
    def FLUXTYPE(self) -> ParserKeyword: ...
    @property
    def FMTHMD(self) -> ParserKeyword: ...
    @property
    def FMTIN(self) -> ParserKeyword: ...
    @property
    def FMTOUT(self) -> ParserKeyword: ...
    @property
    def FMWSET(self) -> ParserKeyword: ...
    @property
    def FOAM(self) -> ParserKeyword: ...
    @property
    def FOAMADS(self) -> ParserKeyword: ...
    @property
    def FOAMDCYO(self) -> ParserKeyword: ...
    @property
    def FOAMDCYW(self) -> ParserKeyword: ...
    @property
    def FOAMFCN(self) -> ParserKeyword: ...
    @property
    def FOAMFRM(self) -> ParserKeyword: ...
    @property
    def FOAMFSC(self) -> ParserKeyword: ...
    @property
    def FOAMFSO(self) -> ParserKeyword: ...
    @property
    def FOAMFST(self) -> ParserKeyword: ...
    @property
    def FOAMFSW(self) -> ParserKeyword: ...
    @property
    def FOAMMOB(self) -> ParserKeyword: ...
    @property
    def FOAMMOBP(self) -> ParserKeyword: ...
    @property
    def FOAMMOBS(self) -> ParserKeyword: ...
    @property
    def FOAMOPTS(self) -> ParserKeyword: ...
    @property
    def FOAMROCK(self) -> ParserKeyword: ...
    @property
    def FORMFEED(self) -> ParserKeyword: ...
    @property
    def FRICTION(self) -> ParserKeyword: ...
    @property
    def FULLIMP(self) -> ParserKeyword: ...
    @property
    def GAS(self) -> ParserKeyword: ...
    @property
    def GASBEGIN(self) -> ParserKeyword: ...
    @property
    def GASCONC(self) -> ParserKeyword: ...
    @property
    def GASDENT(self) -> ParserKeyword: ...
    @property
    def GASEND(self) -> ParserKeyword: ...
    @property
    def GASFCOMP(self) -> ParserKeyword: ...
    @property
    def GASFDECR(self) -> ParserKeyword: ...
    @property
    def GASFDELC(self) -> ParserKeyword: ...
    @property
    def GASFIELD(self) -> ParserKeyword: ...
    @property
    def GASFTARG(self) -> ParserKeyword: ...
    @property
    def GASJT(self) -> ParserKeyword: ...
    @property
    def GASMONTH(self) -> ParserKeyword: ...
    @property
    def GASPERIO(self) -> ParserKeyword: ...
    @property
    def GASSATC(self) -> ParserKeyword: ...
    @property
    def GASVISCT(self) -> ParserKeyword: ...
    @property
    def GASWAT(self) -> ParserKeyword: ...
    @property
    def GASYEAR(self) -> ParserKeyword: ...
    @property
    def GCALECON(self) -> ParserKeyword: ...
    @property
    def GCOMPIDX(self) -> ParserKeyword: ...
    @property
    def GCONCAL(self) -> ParserKeyword: ...
    @property
    def GCONENG(self) -> ParserKeyword: ...
    @property
    def GCONINJE(self) -> ParserKeyword: ...
    @property
    def GCONPRI(self) -> ParserKeyword: ...
    @property
    def GCONPROD(self) -> ParserKeyword: ...
    @property
    def GCONSALE(self) -> ParserKeyword: ...
    @property
    def GCONSUMP(self) -> ParserKeyword: ...
    @property
    def GCONTOL(self) -> ParserKeyword: ...
    @property
    def GCUTBACK(self) -> ParserKeyword: ...
    @property
    def GCUTBACT(self) -> ParserKeyword: ...
    @property
    def GCVD(self) -> ParserKeyword: ...
    @property
    def GDCQ(self) -> ParserKeyword: ...
    @property
    def GDCQECON(self) -> ParserKeyword: ...
    @property
    def GDFILE(self) -> ParserKeyword: ...
    @property
    def GDIMS(self) -> ParserKeyword: ...
    @property
    def GDORIENT(self) -> ParserKeyword: ...
    @property
    def GDRILPOT(self) -> ParserKeyword: ...
    @property
    def GECON(self) -> ParserKeyword: ...
    @property
    def GECONT(self) -> ParserKeyword: ...
    @property
    def GEFAC(self) -> ParserKeyword: ...
    @property
    def GETDATA(self) -> ParserKeyword: ...
    @property
    def GETGLOB(self) -> ParserKeyword: ...
    @property
    def GI(self) -> ParserKeyword: ...
    @property
    def GIALL(self) -> ParserKeyword: ...
    @property
    def GIMODEL(self) -> ParserKeyword: ...
    @property
    def GINODE(self) -> ParserKeyword: ...
    @property
    def GLIFTLIM(self) -> ParserKeyword: ...
    @property
    def GLIFTOPT(self) -> ParserKeyword: ...
    @property
    def GMWSET(self) -> ParserKeyword: ...
    @property
    def GNETDP(self) -> ParserKeyword: ...
    @property
    def GNETINJE(self) -> ParserKeyword: ...
    @property
    def GNETPUMP(self) -> ParserKeyword: ...
    @property
    def GPMAINT(self) -> ParserKeyword: ...
    @property
    def GRADGRUP(self) -> ParserKeyword: ...
    @property
    def GRADRESV(self) -> ParserKeyword: ...
    @property
    def GRADRFT(self) -> ParserKeyword: ...
    @property
    def GRADWELL(self) -> ParserKeyword: ...
    @property
    def GRAVCONS(self) -> ParserKeyword: ...
    @property
    def GRAVDR(self) -> ParserKeyword: ...
    @property
    def GRAVDRB(self) -> ParserKeyword: ...
    @property
    def GRAVDRM(self) -> ParserKeyword: ...
    @property
    def GRAVITY(self) -> ParserKeyword: ...
    @property
    def GRDREACH(self) -> ParserKeyword: ...
    @property
    def GRID(self) -> ParserKeyword: ...
    @property
    def GRIDFILE(self) -> ParserKeyword: ...
    @property
    def GRIDOPTS(self) -> ParserKeyword: ...
    @property
    def GRIDUNIT(self) -> ParserKeyword: ...
    @property
    def GROUP_PROBE(self) -> ParserKeyword: ...
    @property
    def GRUPMAST(self) -> ParserKeyword: ...
    @property
    def GRUPNET(self) -> ParserKeyword: ...
    @property
    def GRUPRIG(self) -> ParserKeyword: ...
    @property
    def GRUPSLAV(self) -> ParserKeyword: ...
    @property
    def GRUPTARG(self) -> ParserKeyword: ...
    @property
    def GRUPTREE(self) -> ParserKeyword: ...
    @property
    def GSATINJE(self) -> ParserKeyword: ...
    @property
    def GSATPROD(self) -> ParserKeyword: ...
    @property
    def GSEPCOND(self) -> ParserKeyword: ...
    @property
    def GSF(self) -> ParserKeyword: ...
    @property
    def GSSCPTST(self) -> ParserKeyword: ...
    @property
    def GSWINGF(self) -> ParserKeyword: ...
    @property
    def GTADD(self) -> ParserKeyword: ...
    @property
    def GTMULT(self) -> ParserKeyword: ...
    @property
    def GUIDECAL(self) -> ParserKeyword: ...
    @property
    def GUIDERAT(self) -> ParserKeyword: ...
    @property
    def GUPFREQ(self) -> ParserKeyword: ...
    @property
    def GWRTWCV(self) -> ParserKeyword: ...
    @property
    def H2SOL(self) -> ParserKeyword: ...
    @property
    def H2STORE(self) -> ParserKeyword: ...
    @property
    def HALFTRAN(self) -> ParserKeyword: ...
    @property
    def HAxxxxxx(self) -> ParserKeyword: ...
    @property
    def HBNUM(self) -> ParserKeyword: ...
    @property
    def HDISP(self) -> ParserKeyword: ...
    @property
    def HEATCR(self) -> ParserKeyword: ...
    @property
    def HEATCRT(self) -> ParserKeyword: ...
    @property
    def HMAQUCT(self) -> ParserKeyword: ...
    @property
    def HMAQUFET(self) -> ParserKeyword: ...
    @property
    def HMAQUNUM(self) -> ParserKeyword: ...
    @property
    def HMDIMS(self) -> ParserKeyword: ...
    @property
    def HMFAULTS(self) -> ParserKeyword: ...
    @property
    def HMMLAQUN(self) -> ParserKeyword: ...
    @property
    def HMMLCTAQ(self) -> ParserKeyword: ...
    @property
    def HMMLFTAQ(self) -> ParserKeyword: ...
    @property
    def HMMLTWCN(self) -> ParserKeyword: ...
    @property
    def HMMULTFT(self) -> ParserKeyword: ...
    @property
    def HMMULTSG(self) -> ParserKeyword: ...
    @property
    def HMMULTxx(self) -> ParserKeyword: ...
    @property
    def HMPROPS(self) -> ParserKeyword: ...
    @property
    def HMROCK(self) -> ParserKeyword: ...
    @property
    def HMROCKT(self) -> ParserKeyword: ...
    @property
    def HMRREF(self) -> ParserKeyword: ...
    @property
    def HMWELCON(self) -> ParserKeyword: ...
    @property
    def HMWPIMLT(self) -> ParserKeyword: ...
    @property
    def HMxxxxxx(self) -> ParserKeyword: ...
    @property
    def HRFIN(self) -> ParserKeyword: ...
    @property
    def HWELLS(self) -> ParserKeyword: ...
    @property
    def HWKRO(self) -> ParserKeyword: ...
    @property
    def HWKRORG(self) -> ParserKeyword: ...
    @property
    def HWKRORW(self) -> ParserKeyword: ...
    @property
    def HWKRW(self) -> ParserKeyword: ...
    @property
    def HWKRWR(self) -> ParserKeyword: ...
    @property
    def HWPCW(self) -> ParserKeyword: ...
    @property
    def HWSNUM(self) -> ParserKeyword: ...
    @property
    def HWSOGCR(self) -> ParserKeyword: ...
    @property
    def HWSOWCR(self) -> ParserKeyword: ...
    @property
    def HWSWCR(self) -> ParserKeyword: ...
    @property
    def HWSWL(self) -> ParserKeyword: ...
    @property
    def HWSWLPC(self) -> ParserKeyword: ...
    @property
    def HWSWU(self) -> ParserKeyword: ...
    @property
    def HXFIN(self) -> ParserKeyword: ...
    @property
    def HYDRHEAD(self) -> ParserKeyword: ...
    @property
    def HYFIN(self) -> ParserKeyword: ...
    @property
    def HYMOBGDR(self) -> ParserKeyword: ...
    @property
    def HYST(self) -> ParserKeyword: ...
    @property
    def HYSTCHCK(self) -> ParserKeyword: ...
    @property
    def HZFIN(self) -> ParserKeyword: ...
    @property
    def IHOST(self) -> ParserKeyword: ...
    @property
    def IMBNUM(self) -> ParserKeyword: ...
    @property
    def IMBNUMMF(self) -> ParserKeyword: ...
    @property
    def IMKRVD(self) -> ParserKeyword: ...
    @property
    def IMPCVD(self) -> ParserKeyword: ...
    @property
    def IMPES(self) -> ParserKeyword: ...
    @property
    def IMPLICIT(self) -> ParserKeyword: ...
    @property
    def IMPORT(self) -> ParserKeyword: ...
    @property
    def IMPTVD(self) -> ParserKeyword: ...
    @property
    def IMSPCVD(self) -> ParserKeyword: ...
    @property
    def INCLUDE(self) -> ParserKeyword: ...
    @property
    def INIT(self) -> ParserKeyword: ...
    @property
    def INRAD(self) -> ParserKeyword: ...
    @property
    def INSPEC(self) -> ParserKeyword: ...
    @property
    def INTPC(self) -> ParserKeyword: ...
    @property
    def IONROCK(self) -> ParserKeyword: ...
    @property
    def IONXROCK(self) -> ParserKeyword: ...
    @property
    def IONXSURF(self) -> ParserKeyword: ...
    @property
    def IPCG(self) -> ParserKeyword: ...
    @property
    def IPCW(self) -> ParserKeyword: ...
    @property
    def ISGCR(self) -> ParserKeyword: ...
    @property
    def ISGL(self) -> ParserKeyword: ...
    @property
    def ISGLPC(self) -> ParserKeyword: ...
    @property
    def ISGU(self) -> ParserKeyword: ...
    @property
    def ISOGCR(self) -> ParserKeyword: ...
    @property
    def ISOLNUM(self) -> ParserKeyword: ...
    @property
    def ISOWCR(self) -> ParserKeyword: ...
    @property
    def ISWCR(self) -> ParserKeyword: ...
    @property
    def ISWL(self) -> ParserKeyword: ...
    @property
    def ISWLPC(self) -> ParserKeyword: ...
    @property
    def ISWU(self) -> ParserKeyword: ...
    @property
    def JFUNC(self) -> ParserKeyword: ...
    @property
    def JFUNCR(self) -> ParserKeyword: ...
    @property
    def KRNUM(self) -> ParserKeyword: ...
    @property
    def KRNUMMF(self) -> ParserKeyword: ...
    @property
    def LAB(self) -> ParserKeyword: ...
    @property
    def LANGMPL(self) -> ParserKeyword: ...
    @property
    def LANGMUIR(self) -> ParserKeyword: ...
    @property
    def LANGSOLV(self) -> ParserKeyword: ...
    @property
    def LCUNIT(self) -> ParserKeyword: ...
    @property
    def LGR(self) -> ParserKeyword: ...
    @property
    def LGRCOPY(self) -> ParserKeyword: ...
    @property
    def LGRFREE(self) -> ParserKeyword: ...
    @property
    def LGRLOCK(self) -> ParserKeyword: ...
    @property
    def LGROFF(self) -> ParserKeyword: ...
    @property
    def LGRON(self) -> ParserKeyword: ...
    @property
    def LICENSES(self) -> ParserKeyword: ...
    @property
    def LIFTOPT(self) -> ParserKeyword: ...
    @property
    def LINCOM(self) -> ParserKeyword: ...
    @property
    def LINKPERM(self) -> ParserKeyword: ...
    @property
    def LIVEOIL(self) -> ParserKeyword: ...
    @property
    def LKRO(self) -> ParserKeyword: ...
    @property
    def LKRORG(self) -> ParserKeyword: ...
    @property
    def LKRORW(self) -> ParserKeyword: ...
    @property
    def LKRW(self) -> ParserKeyword: ...
    @property
    def LKRWR(self) -> ParserKeyword: ...
    @property
    def LOAD(self) -> ParserKeyword: ...
    @property
    def LOWSALT(self) -> ParserKeyword: ...
    @property
    def LPCW(self) -> ParserKeyword: ...
    @property
    def LSALTFNC(self) -> ParserKeyword: ...
    @property
    def LSLTWNUM(self) -> ParserKeyword: ...
    @property
    def LSNUM(self) -> ParserKeyword: ...
    @property
    def LSOGCR(self) -> ParserKeyword: ...
    @property
    def LSOWCR(self) -> ParserKeyword: ...
    @property
    def LSWCR(self) -> ParserKeyword: ...
    @property
    def LSWL(self) -> ParserKeyword: ...
    @property
    def LSWLPC(self) -> ParserKeyword: ...
    @property
    def LSWU(self) -> ParserKeyword: ...
    @property
    def LTOSIGMA(self) -> ParserKeyword: ...
    @property
    def LWKRO(self) -> ParserKeyword: ...
    @property
    def LWKRORG(self) -> ParserKeyword: ...
    @property
    def LWKRORW(self) -> ParserKeyword: ...
    @property
    def LWKRW(self) -> ParserKeyword: ...
    @property
    def LWKRWR(self) -> ParserKeyword: ...
    @property
    def LWPCW(self) -> ParserKeyword: ...
    @property
    def LWSLTNUM(self) -> ParserKeyword: ...
    @property
    def LWSNUM(self) -> ParserKeyword: ...
    @property
    def LWSOGCR(self) -> ParserKeyword: ...
    @property
    def LWSOWCR(self) -> ParserKeyword: ...
    @property
    def LWSWCR(self) -> ParserKeyword: ...
    @property
    def LWSWL(self) -> ParserKeyword: ...
    @property
    def LWSWLPC(self) -> ParserKeyword: ...
    @property
    def LWSWU(self) -> ParserKeyword: ...
    @property
    def LX(self) -> ParserKeyword: ...
    @property
    def LXFIN(self) -> ParserKeyword: ...
    @property
    def LY(self) -> ParserKeyword: ...
    @property
    def LYFIN(self) -> ParserKeyword: ...
    @property
    def LZ(self) -> ParserKeyword: ...
    @property
    def LZFIN(self) -> ParserKeyword: ...
    @property
    def MAPAXES(self) -> ParserKeyword: ...
    @property
    def MAPUNITS(self) -> ParserKeyword: ...
    @property
    def MASSFLOW(self) -> ParserKeyword: ...
    @property
    def MATCORR(self) -> ParserKeyword: ...
    @property
    def MAXVALUE(self) -> ParserKeyword: ...
    @property
    def MECH(self) -> ParserKeyword: ...
    @property
    def MEMORY(self) -> ParserKeyword: ...
    @property
    def MESSAGE(self) -> ParserKeyword: ...
    @property
    def MESSAGES(self) -> ParserKeyword: ...
    @property
    def MESSOPTS(self) -> ParserKeyword: ...
    @property
    def MESSSRVC(self) -> ParserKeyword: ...
    @property
    def METRIC(self) -> ParserKeyword: ...
    @property
    def MICP(self) -> ParserKeyword: ...
    @property
    def MICPPARA(self) -> ParserKeyword: ...
    @property
    def MINNNCT(self) -> ParserKeyword: ...
    @property
    def MINNPCOL(self) -> ParserKeyword: ...
    @property
    def MINPORV(self) -> ParserKeyword: ...
    @property
    def MINPV(self) -> ParserKeyword: ...
    @property
    def MINPVV(self) -> ParserKeyword: ...
    @property
    def MINVALUE(self) -> ParserKeyword: ...
    @property
    def MISC(self) -> ParserKeyword: ...
    @property
    def MISCIBLE(self) -> ParserKeyword: ...
    @property
    def MISCNUM(self) -> ParserKeyword: ...
    @property
    def MLANG(self) -> ParserKeyword: ...
    @property
    def MLANGSLV(self) -> ParserKeyword: ...
    @property
    def MONITOR(self) -> ParserKeyword: ...
    @property
    def MPFANUM(self) -> ParserKeyword: ...
    @property
    def MPFNNC(self) -> ParserKeyword: ...
    @property
    def MSFN(self) -> ParserKeyword: ...
    @property
    def MSGFILE(self) -> ParserKeyword: ...
    @property
    def MSUM_PROBE(self) -> ParserKeyword: ...
    @property
    def MULSGGD(self) -> ParserKeyword: ...
    @property
    def MULSGGDV(self) -> ParserKeyword: ...
    @property
    def MULTFLT(self) -> ParserKeyword: ...
    @property
    def MULTIN(self) -> ParserKeyword: ...
    @property
    def MULTIPLY(self) -> ParserKeyword: ...
    @property
    def MULTIREG(self) -> ParserKeyword: ...
    @property
    def MULTNUM(self) -> ParserKeyword: ...
    @property
    def MULTOUT(self) -> ParserKeyword: ...
    @property
    def MULTOUTS(self) -> ParserKeyword: ...
    @property
    def MULTPV(self) -> ParserKeyword: ...
    @property
    def MULTREAL(self) -> ParserKeyword: ...
    @property
    def MULTREGD(self) -> ParserKeyword: ...
    @property
    def MULTREGH(self) -> ParserKeyword: ...
    @property
    def MULTREGP(self) -> ParserKeyword: ...
    @property
    def MULTREGT(self) -> ParserKeyword: ...
    @property
    def MULTSIG(self) -> ParserKeyword: ...
    @property
    def MULTSIGV(self) -> ParserKeyword: ...
    @property
    def MULT_XYZ(self) -> ParserKeyword: ...
    @property
    def MW(self) -> ParserKeyword: ...
    @property
    def MWS(self) -> ParserKeyword: ...
    @property
    def NARROW(self) -> ParserKeyword: ...
    @property
    def NCOMPS(self) -> ParserKeyword: ...
    @property
    def NCONSUMP(self) -> ParserKeyword: ...
    @property
    def NEFAC(self) -> ParserKeyword: ...
    @property
    def NETBALAN(self) -> ParserKeyword: ...
    @property
    def NETCOMPA(self) -> ParserKeyword: ...
    @property
    def NETWORK(self) -> ParserKeyword: ...
    @property
    def NETWORK_PROBE(self) -> ParserKeyword: ...
    @property
    def NEWTRAN(self) -> ParserKeyword: ...
    @property
    def NEXTSTEP(self) -> ParserKeyword: ...
    @property
    def NEXTSTPL(self) -> ParserKeyword: ...
    @property
    def NINENUM(self) -> ParserKeyword: ...
    @property
    def NINEPOIN(self) -> ParserKeyword: ...
    @property
    def NMATOPTS(self) -> ParserKeyword: ...
    @property
    def NMATRIX(self) -> ParserKeyword: ...
    @property
    def NMESSAGE(self) -> ParserKeyword: ...
    @property
    def NNC(self) -> ParserKeyword: ...
    @property
    def NNEWTF(self) -> ParserKeyword: ...
    @property
    def NOCASC(self) -> ParserKeyword: ...
    @property
    def NODEPROP(self) -> ParserKeyword: ...
    @property
    def NODPPM(self) -> ParserKeyword: ...
    @property
    def NOECHO(self) -> ParserKeyword: ...
    @property
    def NOGGF(self) -> ParserKeyword: ...
    @property
    def NOGRAV(self) -> ParserKeyword: ...
    @property
    def NOHMD(self) -> ParserKeyword: ...
    @property
    def NOHMO(self) -> ParserKeyword: ...
    @property
    def NOHYST(self) -> ParserKeyword: ...
    @property
    def NOINSPEC(self) -> ParserKeyword: ...
    @property
    def NOMONITO(self) -> ParserKeyword: ...
    @property
    def NONNC(self) -> ParserKeyword: ...
    @property
    def NORSSPEC(self) -> ParserKeyword: ...
    @property
    def NOSIM(self) -> ParserKeyword: ...
    @property
    def NOWARN(self) -> ParserKeyword: ...
    @property
    def NOWARNEP(self) -> ParserKeyword: ...
    @property
    def NRSOUT(self) -> ParserKeyword: ...
    @property
    def NSTACK(self) -> ParserKeyword: ...
    @property
    def NTG(self) -> ParserKeyword: ...
    @property
    def NUMRES(self) -> ParserKeyword: ...
    @property
    def NUPCOL(self) -> ParserKeyword: ...
    @property
    def NWATREM(self) -> ParserKeyword: ...
    @property
    def NXFIN(self) -> ParserKeyword: ...
    @property
    def NYFIN(self) -> ParserKeyword: ...
    @property
    def NZFIN(self) -> ParserKeyword: ...
    @property
    def OCOMPIDX(self) -> ParserKeyword: ...
    @property
    def OFM(self) -> ParserKeyword: ...
    @property
    def OIL(self) -> ParserKeyword: ...
    @property
    def OILAPI(self) -> ParserKeyword: ...
    @property
    def OILCOMPR(self) -> ParserKeyword: ...
    @property
    def OILDENT(self) -> ParserKeyword: ...
    @property
    def OILJT(self) -> ParserKeyword: ...
    @property
    def OILMW(self) -> ParserKeyword: ...
    @property
    def OILVISCT(self) -> ParserKeyword: ...
    @property
    def OILVTIM(self) -> ParserKeyword: ...
    @property
    def OLDTRAN(self) -> ParserKeyword: ...
    @property
    def OLDTRANR(self) -> ParserKeyword: ...
    @property
    def OPERATE(self) -> ParserKeyword: ...
    @property
    def OPERATER(self) -> ParserKeyword: ...
    @property
    def OPERNUM(self) -> ParserKeyword: ...
    @property
    def OPTIONS(self) -> ParserKeyword: ...
    @property
    def OPTIONS3(self) -> ParserKeyword: ...
    @property
    def OUTRAD(self) -> ParserKeyword: ...
    @property
    def OUTSOL(self) -> ParserKeyword: ...
    @property
    def OVERBURD(self) -> ParserKeyword: ...
    @property
    def PARALLEL(self) -> ParserKeyword: ...
    @property
    def PARAOPTS(self) -> ParserKeyword: ...
    @property
    def PARTTRAC(self) -> ParserKeyword: ...
    @property
    def PATHS(self) -> ParserKeyword: ...
    @property
    def PBUB(self) -> ParserKeyword: ...
    @property
    def PBVD(self) -> ParserKeyword: ...
    @property
    def PCFACT(self) -> ParserKeyword: ...
    @property
    def PCG(self) -> ParserKeyword: ...
    @property
    def PCG32D(self) -> ParserKeyword: ...
    @property
    def PCRIT(self) -> ParserKeyword: ...
    @property
    def PCW(self) -> ParserKeyword: ...
    @property
    def PCW32D(self) -> ParserKeyword: ...
    @property
    def PDEW(self) -> ParserKeyword: ...
    @property
    def PDVD(self) -> ParserKeyword: ...
    @property
    def PEBI(self) -> ParserKeyword: ...
    @property
    def PECOEFS(self) -> ParserKeyword: ...
    @property
    def PEDIMS(self) -> ParserKeyword: ...
    @property
    def PEGTABX(self) -> ParserKeyword: ...
    @property
    def PEKTABX(self) -> ParserKeyword: ...
    @property
    def PENUM(self) -> ParserKeyword: ...
    @property
    def PERFORMANCE_PROBE(self) -> ParserKeyword: ...
    @property
    def PERMAVE(self) -> ParserKeyword: ...
    @property
    def PERMFACT(self) -> ParserKeyword: ...
    @property
    def PERMJFUN(self) -> ParserKeyword: ...
    @property
    def PERMR(self) -> ParserKeyword: ...
    @property
    def PERMTHT(self) -> ParserKeyword: ...
    @property
    def PERMX(self) -> ParserKeyword: ...
    @property
    def PERMXY(self) -> ParserKeyword: ...
    @property
    def PERMY(self) -> ParserKeyword: ...
    @property
    def PERMYZ(self) -> ParserKeyword: ...
    @property
    def PERMZ(self) -> ParserKeyword: ...
    @property
    def PERMZX(self) -> ParserKeyword: ...
    @property
    def PETGRID(self) -> ParserKeyword: ...
    @property
    def PETOPTS(self) -> ParserKeyword: ...
    @property
    def PICOND(self) -> ParserKeyword: ...
    @property
    def PIMTDIMS(self) -> ParserKeyword: ...
    @property
    def PIMULTAB(self) -> ParserKeyword: ...
    @property
    def PINCH(self) -> ParserKeyword: ...
    @property
    def PINCHNUM(self) -> ParserKeyword: ...
    @property
    def PINCHOUT(self) -> ParserKeyword: ...
    @property
    def PINCHREG(self) -> ParserKeyword: ...
    @property
    def PINCHXY(self) -> ParserKeyword: ...
    @property
    def PINTDIMS(self) -> ParserKeyword: ...
    @property
    def PLMIXNUM(self) -> ParserKeyword: ...
    @property
    def PLMIXPAR(self) -> ParserKeyword: ...
    @property
    def PLYADS(self) -> ParserKeyword: ...
    @property
    def PLYADSS(self) -> ParserKeyword: ...
    @property
    def PLYATEMP(self) -> ParserKeyword: ...
    @property
    def PLYCAMAX(self) -> ParserKeyword: ...
    @property
    def PLYDHFLF(self) -> ParserKeyword: ...
    @property
    def PLYESAL(self) -> ParserKeyword: ...
    @property
    def PLYKRRF(self) -> ParserKeyword: ...
    @property
    def PLYMAX(self) -> ParserKeyword: ...
    @property
    def PLYMWINJ(self) -> ParserKeyword: ...
    @property
    def PLYOPTS(self) -> ParserKeyword: ...
    @property
    def PLYRMDEN(self) -> ParserKeyword: ...
    @property
    def PLYROCK(self) -> ParserKeyword: ...
    @property
    def PLYROCKM(self) -> ParserKeyword: ...
    @property
    def PLYSHEAR(self) -> ParserKeyword: ...
    @property
    def PLYSHLOG(self) -> ParserKeyword: ...
    @property
    def PLYTRRF(self) -> ParserKeyword: ...
    @property
    def PLYTRRFA(self) -> ParserKeyword: ...
    @property
    def PLYVISC(self) -> ParserKeyword: ...
    @property
    def PLYVISCS(self) -> ParserKeyword: ...
    @property
    def PLYVISCT(self) -> ParserKeyword: ...
    @property
    def PLYVMH(self) -> ParserKeyword: ...
    @property
    def PLYVSCST(self) -> ParserKeyword: ...
    @property
    def PMAX(self) -> ParserKeyword: ...
    @property
    def PMISC(self) -> ParserKeyword: ...
    @property
    def POELCOEF(self) -> ParserKeyword: ...
    @property
    def POLYMER(self) -> ParserKeyword: ...
    @property
    def POLYMW(self) -> ParserKeyword: ...
    @property
    def PORO(self) -> ParserKeyword: ...
    @property
    def PORV(self) -> ParserKeyword: ...
    @property
    def PPCWMAX(self) -> ParserKeyword: ...
    @property
    def PRATIO(self) -> ParserKeyword: ...
    @property
    def PRECSALT(self) -> ParserKeyword: ...
    @property
    def PREF(self) -> ParserKeyword: ...
    @property
    def PREFS(self) -> ParserKeyword: ...
    @property
    def PRESSURE(self) -> ParserKeyword: ...
    @property
    def PRIORITY(self) -> ParserKeyword: ...
    @property
    def PROPS(self) -> ParserKeyword: ...
    @property
    def PRORDER(self) -> ParserKeyword: ...
    @property
    def PRVD(self) -> ParserKeyword: ...
    @property
    def PSTEADY(self) -> ParserKeyword: ...
    @property
    def PSWRG(self) -> ParserKeyword: ...
    @property
    def PSWRO(self) -> ParserKeyword: ...
    @property
    def PVCDO(self) -> ParserKeyword: ...
    @property
    def PVCO(self) -> ParserKeyword: ...
    @property
    def PVDG(self) -> ParserKeyword: ...
    @property
    def PVDO(self) -> ParserKeyword: ...
    @property
    def PVDS(self) -> ParserKeyword: ...
    @property
    def PVTG(self) -> ParserKeyword: ...
    @property
    def PVTGW(self) -> ParserKeyword: ...
    @property
    def PVTGWO(self) -> ParserKeyword: ...
    @property
    def PVTNUM(self) -> ParserKeyword: ...
    @property
    def PVTO(self) -> ParserKeyword: ...
    @property
    def PVTSOL(self) -> ParserKeyword: ...
    @property
    def PVTW(self) -> ParserKeyword: ...
    @property
    def PVTWSALT(self) -> ParserKeyword: ...
    @property
    def PVT_M(self) -> ParserKeyword: ...
    @property
    def PVZG(self) -> ParserKeyword: ...
    @property
    def PYACTION(self) -> ParserKeyword: ...
    @property
    def PYINPUT(self) -> ParserKeyword: ...
    @property
    def QDRILL(self) -> ParserKeyword: ...
    @property
    def QHRATING(self) -> ParserKeyword: ...
    @property
    def QMOBIL(self) -> ParserKeyword: ...
    @property
    def RADFIN(self) -> ParserKeyword: ...
    @property
    def RADFIN4(self) -> ParserKeyword: ...
    @property
    def RADIAL(self) -> ParserKeyword: ...
    @property
    def RAINFALL(self) -> ParserKeyword: ...
    @property
    def RBEDCONT(self) -> ParserKeyword: ...
    @property
    def RCMASTS(self) -> ParserKeyword: ...
    @property
    def REACHES(self) -> ParserKeyword: ...
    @property
    def READDATA(self) -> ParserKeyword: ...
    @property
    def REFINE(self) -> ParserKeyword: ...
    @property
    def REGDIMS(self) -> ParserKeyword: ...
    @property
    def REGION2REGION_PROBE(self) -> ParserKeyword: ...
    @property
    def REGION2REGION_PROBE_E300(self) -> ParserKeyword: ...
    @property
    def REGIONS(self) -> ParserKeyword: ...
    @property
    def REGION_PROBE(self) -> ParserKeyword: ...
    @property
    def REGION_PROBE_OPM(self) -> ParserKeyword: ...
    @property
    def RESIDNUM(self) -> ParserKeyword: ...
    @property
    def RESTART(self) -> ParserKeyword: ...
    @property
    def RESVNUM(self) -> ParserKeyword: ...
    @property
    def RHO(self) -> ParserKeyword: ...
    @property
    def RIVDEBUG(self) -> ParserKeyword: ...
    @property
    def RIVERSYS(self) -> ParserKeyword: ...
    @property
    def RIVRDIMS(self) -> ParserKeyword: ...
    @property
    def RIVRPROP(self) -> ParserKeyword: ...
    @property
    def RIVRXSEC(self) -> ParserKeyword: ...
    @property
    def RIVSALT(self) -> ParserKeyword: ...
    @property
    def RIVTRACE(self) -> ParserKeyword: ...
    @property
    def RKTRMDIR(self) -> ParserKeyword: ...
    @property
    def ROCK(self) -> ParserKeyword: ...
    @property
    def ROCK2D(self) -> ParserKeyword: ...
    @property
    def ROCK2DTR(self) -> ParserKeyword: ...
    @property
    def ROCKCOMP(self) -> ParserKeyword: ...
    @property
    def ROCKFRAC(self) -> ParserKeyword: ...
    @property
    def ROCKNUM(self) -> ParserKeyword: ...
    @property
    def ROCKOPTS(self) -> ParserKeyword: ...
    @property
    def ROCKPAMA(self) -> ParserKeyword: ...
    @property
    def ROCKTAB(self) -> ParserKeyword: ...
    @property
    def ROCKTABH(self) -> ParserKeyword: ...
    @property
    def ROCKTABW(self) -> ParserKeyword: ...
    @property
    def ROCKTHSG(self) -> ParserKeyword: ...
    @property
    def ROCKTSIG(self) -> ParserKeyword: ...
    @property
    def ROCKV(self) -> ParserKeyword: ...
    @property
    def ROCKWNOD(self) -> ParserKeyword: ...
    @property
    def RPTCPL(self) -> ParserKeyword: ...
    @property
    def RPTGRID(self) -> ParserKeyword: ...
    @property
    def RPTGRIDL(self) -> ParserKeyword: ...
    @property
    def RPTHMD(self) -> ParserKeyword: ...
    @property
    def RPTHMG(self) -> ParserKeyword: ...
    @property
    def RPTHMW(self) -> ParserKeyword: ...
    @property
    def RPTINIT(self) -> ParserKeyword: ...
    @property
    def RPTISOL(self) -> ParserKeyword: ...
    @property
    def RPTONLY(self) -> ParserKeyword: ...
    @property
    def RPTONLYO(self) -> ParserKeyword: ...
    @property
    def RPTPROPS(self) -> ParserKeyword: ...
    @property
    def RPTREGS(self) -> ParserKeyword: ...
    @property
    def RPTRST(self) -> ParserKeyword: ...
    @property
    def RPTRUNSP(self) -> ParserKeyword: ...
    @property
    def RPTSCHED(self) -> ParserKeyword: ...
    @property
    def RPTSMRY(self) -> ParserKeyword: ...
    @property
    def RPTSOL(self) -> ParserKeyword: ...
    @property
    def RS(self) -> ParserKeyword: ...
    @property
    def RSCONST(self) -> ParserKeyword: ...
    @property
    def RSCONSTT(self) -> ParserKeyword: ...
    @property
    def RSGI(self) -> ParserKeyword: ...
    @property
    def RSSPEC(self) -> ParserKeyword: ...
    @property
    def RSVD(self) -> ParserKeyword: ...
    @property
    def RTEMP(self) -> ParserKeyword: ...
    @property
    def RTEMPA(self) -> ParserKeyword: ...
    @property
    def RTEMPVD(self) -> ParserKeyword: ...
    @property
    def RUNSPEC(self) -> ParserKeyword: ...
    @property
    def RUNSUM(self) -> ParserKeyword: ...
    @property
    def RV(self) -> ParserKeyword: ...
    @property
    def RVCONST(self) -> ParserKeyword: ...
    @property
    def RVCONSTT(self) -> ParserKeyword: ...
    @property
    def RVGI(self) -> ParserKeyword: ...
    @property
    def RVVD(self) -> ParserKeyword: ...
    @property
    def RVW(self) -> ParserKeyword: ...
    @property
    def RVWVD(self) -> ParserKeyword: ...
    @property
    def RWGSALT(self) -> ParserKeyword: ...
    @property
    def SALINITY(self) -> ParserKeyword: ...
    @property
    def SALT(self) -> ParserKeyword: ...
    @property
    def SALTNODE(self) -> ParserKeyword: ...
    @property
    def SALTP(self) -> ParserKeyword: ...
    @property
    def SALTPVD(self) -> ParserKeyword: ...
    @property
    def SALTREST(self) -> ParserKeyword: ...
    @property
    def SALTSOL(self) -> ParserKeyword: ...
    @property
    def SALTVD(self) -> ParserKeyword: ...
    @property
    def SAMG(self) -> ParserKeyword: ...
    @property
    def SATNUM(self) -> ParserKeyword: ...
    @property
    def SATOPTS(self) -> ParserKeyword: ...
    @property
    def SAVE(self) -> ParserKeyword: ...
    @property
    def SBIOF(self) -> ParserKeyword: ...
    @property
    def SCALC(self) -> ParserKeyword: ...
    @property
    def SCALECRS(self) -> ParserKeyword: ...
    @property
    def SCALELIM(self) -> ParserKeyword: ...
    @property
    def SCDATAB(self) -> ParserKeyword: ...
    @property
    def SCDETAB(self) -> ParserKeyword: ...
    @property
    def SCDPDIMS(self) -> ParserKeyword: ...
    @property
    def SCDPTAB(self) -> ParserKeyword: ...
    @property
    def SCDPTRAC(self) -> ParserKeyword: ...
    @property
    def SCHEDULE(self) -> ParserKeyword: ...
    @property
    def SCVD(self) -> ParserKeyword: ...
    @property
    def SDENSITY(self) -> ParserKeyword: ...
    @property
    def SEGMENT_PROBE(self) -> ParserKeyword: ...
    @property
    def SEPARATE(self) -> ParserKeyword: ...
    @property
    def SEPVALS(self) -> ParserKeyword: ...
    @property
    def SFOAM(self) -> ParserKeyword: ...
    @property
    def SGAS(self) -> ParserKeyword: ...
    @property
    def SGCR(self) -> ParserKeyword: ...
    @property
    def SGCWMIS(self) -> ParserKeyword: ...
    @property
    def SGF32D(self) -> ParserKeyword: ...
    @property
    def SGFN(self) -> ParserKeyword: ...
    @property
    def SGL(self) -> ParserKeyword: ...
    @property
    def SGLPC(self) -> ParserKeyword: ...
    @property
    def SGOF(self) -> ParserKeyword: ...
    @property
    def SGOFLET(self) -> ParserKeyword: ...
    @property
    def SGU(self) -> ParserKeyword: ...
    @property
    def SGWFN(self) -> ParserKeyword: ...
    @property
    def SHRATE(self) -> ParserKeyword: ...
    @property
    def SIGMA(self) -> ParserKeyword: ...
    @property
    def SIGMAGDV(self) -> ParserKeyword: ...
    @property
    def SIGMATH(self) -> ParserKeyword: ...
    @property
    def SIGMAV(self) -> ParserKeyword: ...
    @property
    def SIMULATE(self) -> ParserKeyword: ...
    @property
    def SKIP(self) -> ParserKeyword: ...
    @property
    def SKIP100(self) -> ParserKeyword: ...
    @property
    def SKIP300(self) -> ParserKeyword: ...
    @property
    def SKIPREST(self) -> ParserKeyword: ...
    @property
    def SKPRPOLY(self) -> ParserKeyword: ...
    @property
    def SKPRWAT(self) -> ParserKeyword: ...
    @property
    def SKRO(self) -> ParserKeyword: ...
    @property
    def SKRORG(self) -> ParserKeyword: ...
    @property
    def SKRORW(self) -> ParserKeyword: ...
    @property
    def SKRW(self) -> ParserKeyword: ...
    @property
    def SKRWR(self) -> ParserKeyword: ...
    @property
    def SLAVES(self) -> ParserKeyword: ...
    @property
    def SLGOF(self) -> ParserKeyword: ...
    @property
    def SMICR(self) -> ParserKeyword: ...
    @property
    def SMRYDIMS(self) -> ParserKeyword: ...
    @property
    def SMULTX(self) -> ParserKeyword: ...
    @property
    def SMULTY(self) -> ParserKeyword: ...
    @property
    def SMULTZ(self) -> ParserKeyword: ...
    @property
    def SOCRS(self) -> ParserKeyword: ...
    @property
    def SOF2(self) -> ParserKeyword: ...
    @property
    def SOF3(self) -> ParserKeyword: ...
    @property
    def SOF32D(self) -> ParserKeyword: ...
    @property
    def SOGCR(self) -> ParserKeyword: ...
    @property
    def SOIL(self) -> ParserKeyword: ...
    @property
    def SOLID(self) -> ParserKeyword: ...
    @property
    def SOLUTION(self) -> ParserKeyword: ...
    @property
    def SOLVCONC(self) -> ParserKeyword: ...
    @property
    def SOLVDIMS(self) -> ParserKeyword: ...
    @property
    def SOLVDIRS(self) -> ParserKeyword: ...
    @property
    def SOLVENT(self) -> ParserKeyword: ...
    @property
    def SOLVFRAC(self) -> ParserKeyword: ...
    @property
    def SOLVNUM(self) -> ParserKeyword: ...
    @property
    def SOMGAS(self) -> ParserKeyword: ...
    @property
    def SOMWAT(self) -> ParserKeyword: ...
    @property
    def SORWMIS(self) -> ParserKeyword: ...
    @property
    def SOURCE(self) -> ParserKeyword: ...
    @property
    def SOWCR(self) -> ParserKeyword: ...
    @property
    def SOXYG(self) -> ParserKeyword: ...
    @property
    def SPECGRID(self) -> ParserKeyword: ...
    @property
    def SPECHEAT(self) -> ParserKeyword: ...
    @property
    def SPECROCK(self) -> ParserKeyword: ...
    @property
    def SPIDER(self) -> ParserKeyword: ...
    @property
    def SPOLY(self) -> ParserKeyword: ...
    @property
    def SPOLYMW(self) -> ParserKeyword: ...
    @property
    def SSFN(self) -> ParserKeyword: ...
    @property
    def SSGCR(self) -> ParserKeyword: ...
    @property
    def SSGL(self) -> ParserKeyword: ...
    @property
    def SSOGCR(self) -> ParserKeyword: ...
    @property
    def SSOL(self) -> ParserKeyword: ...
    @property
    def SSOWCR(self) -> ParserKeyword: ...
    @property
    def SSWCR(self) -> ParserKeyword: ...
    @property
    def SSWL(self) -> ParserKeyword: ...
    @property
    def SSWU(self) -> ParserKeyword: ...
    @property
    def START(self) -> ParserKeyword: ...
    @property
    def STCOND(self) -> ParserKeyword: ...
    @property
    def STOG(self) -> ParserKeyword: ...
    @property
    def STONE(self) -> ParserKeyword: ...
    @property
    def STONE1(self) -> ParserKeyword: ...
    @property
    def STONE1EX(self) -> ParserKeyword: ...
    @property
    def STONE2(self) -> ParserKeyword: ...
    @property
    def STOW(self) -> ParserKeyword: ...
    @property
    def STREQUIL(self) -> ParserKeyword: ...
    @property
    def STRESSEQUILNUM(self) -> ParserKeyword: ...
    @property
    def STWG(self) -> ParserKeyword: ...
    @property
    def SUMMARY(self) -> ParserKeyword: ...
    @property
    def SUMTHIN(self) -> ParserKeyword: ...
    @property
    def SUREA(self) -> ParserKeyword: ...
    @property
    def SURF(self) -> ParserKeyword: ...
    @property
    def SURFACT(self) -> ParserKeyword: ...
    @property
    def SURFACTW(self) -> ParserKeyword: ...
    @property
    def SURFADDW(self) -> ParserKeyword: ...
    @property
    def SURFADS(self) -> ParserKeyword: ...
    @property
    def SURFCAPD(self) -> ParserKeyword: ...
    @property
    def SURFESAL(self) -> ParserKeyword: ...
    @property
    def SURFNUM(self) -> ParserKeyword: ...
    @property
    def SURFOPTS(self) -> ParserKeyword: ...
    @property
    def SURFROCK(self) -> ParserKeyword: ...
    @property
    def SURFST(self) -> ParserKeyword: ...
    @property
    def SURFSTES(self) -> ParserKeyword: ...
    @property
    def SURFVISC(self) -> ParserKeyword: ...
    @property
    def SURFWNUM(self) -> ParserKeyword: ...
    @property
    def SWAT(self) -> ParserKeyword: ...
    @property
    def SWATINIT(self) -> ParserKeyword: ...
    @property
    def SWCR(self) -> ParserKeyword: ...
    @property
    def SWF32D(self) -> ParserKeyword: ...
    @property
    def SWFN(self) -> ParserKeyword: ...
    @property
    def SWINGFAC(self) -> ParserKeyword: ...
    @property
    def SWL(self) -> ParserKeyword: ...
    @property
    def SWLPC(self) -> ParserKeyword: ...
    @property
    def SWOF(self) -> ParserKeyword: ...
    @property
    def SWOFLET(self) -> ParserKeyword: ...
    @property
    def SWU(self) -> ParserKeyword: ...
    @property
    def TABDIMS(self) -> ParserKeyword: ...
    @property
    def TBLK(self) -> ParserKeyword: ...
    @property
    def TCRIT(self) -> ParserKeyword: ...
    @property
    def TEMP(self) -> ParserKeyword: ...
    @property
    def TEMPI(self) -> ParserKeyword: ...
    @property
    def TEMPNODE(self) -> ParserKeyword: ...
    @property
    def TEMPTVD(self) -> ParserKeyword: ...
    @property
    def TEMPVD(self) -> ParserKeyword: ...
    @property
    def THCGAS(self) -> ParserKeyword: ...
    @property
    def THCO2MIX(self) -> ParserKeyword: ...
    @property
    def THCOIL(self) -> ParserKeyword: ...
    @property
    def THCONR(self) -> ParserKeyword: ...
    @property
    def THCONSF(self) -> ParserKeyword: ...
    @property
    def THCROCK(self) -> ParserKeyword: ...
    @property
    def THCWATER(self) -> ParserKeyword: ...
    @property
    def THELCOEF(self) -> ParserKeyword: ...
    @property
    def THERMAL(self) -> ParserKeyword: ...
    @property
    def THERMEXR(self) -> ParserKeyword: ...
    @property
    def THPRES(self) -> ParserKeyword: ...
    @property
    def THPRESFT(self) -> ParserKeyword: ...
    @property
    def TIGHTEN(self) -> ParserKeyword: ...
    @property
    def TIGHTENP(self) -> ParserKeyword: ...
    @property
    def TIME(self) -> ParserKeyword: ...
    @property
    def TITLE(self) -> ParserKeyword: ...
    @property
    def TLMIXPAR(self) -> ParserKeyword: ...
    @property
    def TLPMIXPA(self) -> ParserKeyword: ...
    @property
    def TNUM(self) -> ParserKeyword: ...
    @property
    def TOLCRIT(self) -> ParserKeyword: ...
    @property
    def TOPS(self) -> ParserKeyword: ...
    @property
    def TPAMEPS(self) -> ParserKeyword: ...
    @property
    def TPAMEPSS(self) -> ParserKeyword: ...
    @property
    def TRACER(self) -> ParserKeyword: ...
    @property
    def TRACERKM(self) -> ParserKeyword: ...
    @property
    def TRACERKP(self) -> ParserKeyword: ...
    @property
    def TRACERS(self) -> ParserKeyword: ...
    @property
    def TRACITVD(self) -> ParserKeyword: ...
    @property
    def TRACTVD(self) -> ParserKeyword: ...
    @property
    def TRADS(self) -> ParserKeyword: ...
    @property
    def TRANGL(self) -> ParserKeyword: ...
    @property
    def TRANR(self) -> ParserKeyword: ...
    @property
    def TRANTHT(self) -> ParserKeyword: ...
    @property
    def TRANX(self) -> ParserKeyword: ...
    @property
    def TRANY(self) -> ParserKeyword: ...
    @property
    def TRANZ(self) -> ParserKeyword: ...
    @property
    def TRDCY(self) -> ParserKeyword: ...
    @property
    def TRDIF(self) -> ParserKeyword: ...
    @property
    def TRDIS(self) -> ParserKeyword: ...
    @property
    def TREF(self) -> ParserKeyword: ...
    @property
    def TREFS(self) -> ParserKeyword: ...
    @property
    def TRKPF(self) -> ParserKeyword: ...
    @property
    def TRNHD(self) -> ParserKeyword: ...
    @property
    def TRPLPORO(self) -> ParserKeyword: ...
    @property
    def TRROCK(self) -> ParserKeyword: ...
    @property
    def TSTEP(self) -> ParserKeyword: ...
    @property
    def TUNING(self) -> ParserKeyword: ...
    @property
    def TUNINGDP(self) -> ParserKeyword: ...
    @property
    def TUNINGH(self) -> ParserKeyword: ...
    @property
    def TUNINGL(self) -> ParserKeyword: ...
    @property
    def TUNINGS(self) -> ParserKeyword: ...
    @property
    def TVDP(self) -> ParserKeyword: ...
    @property
    def TZONE(self) -> ParserKeyword: ...
    @property
    def UDADIMS(self) -> ParserKeyword: ...
    @property
    def UDQ(self) -> ParserKeyword: ...
    @property
    def UDQDIMS(self) -> ParserKeyword: ...
    @property
    def UDQPARAM(self) -> ParserKeyword: ...
    @property
    def UDT(self) -> ParserKeyword: ...
    @property
    def UDTDIMS(self) -> ParserKeyword: ...
    @property
    def UNCODHMD(self) -> ParserKeyword: ...
    @property
    def UNIFIN(self) -> ParserKeyword: ...
    @property
    def UNIFOUT(self) -> ParserKeyword: ...
    @property
    def UNIFOUTS(self) -> ParserKeyword: ...
    @property
    def UNIFSAVE(self) -> ParserKeyword: ...
    @property
    def USECUPL(self) -> ParserKeyword: ...
    @property
    def USEFLUX(self) -> ParserKeyword: ...
    @property
    def USENOFLO(self) -> ParserKeyword: ...
    @property
    def VAPOIL(self) -> ParserKeyword: ...
    @property
    def VAPPARS(self) -> ParserKeyword: ...
    @property
    def VAPWAT(self) -> ParserKeyword: ...
    @property
    def VCRIT(self) -> ParserKeyword: ...
    @property
    def VDFLOW(self) -> ParserKeyword: ...
    @property
    def VDFLOWR(self) -> ParserKeyword: ...
    @property
    def VE(self) -> ParserKeyword: ...
    @property
    def VEDEBUG(self) -> ParserKeyword: ...
    @property
    def VEFIN(self) -> ParserKeyword: ...
    @property
    def VEFRAC(self) -> ParserKeyword: ...
    @property
    def VEFRACP(self) -> ParserKeyword: ...
    @property
    def VEFRACPV(self) -> ParserKeyword: ...
    @property
    def VEFRACV(self) -> ParserKeyword: ...
    @property
    def VFPCHK(self) -> ParserKeyword: ...
    @property
    def VFPIDIMS(self) -> ParserKeyword: ...
    @property
    def VFPINJ(self) -> ParserKeyword: ...
    @property
    def VFPPDIMS(self) -> ParserKeyword: ...
    @property
    def VFPPROD(self) -> ParserKeyword: ...
    @property
    def VFPTABL(self) -> ParserKeyword: ...
    @property
    def VISAGE(self) -> ParserKeyword: ...
    @property
    def VISCD(self) -> ParserKeyword: ...
    @property
    def VISCREF(self) -> ParserKeyword: ...
    @property
    def VISDATES(self) -> ParserKeyword: ...
    @property
    def VISOPTS(self) -> ParserKeyword: ...
    @property
    def WAGHYSTR(self) -> ParserKeyword: ...
    @property
    def WAITBAL(self) -> ParserKeyword: ...
    @property
    def WALKALIN(self) -> ParserKeyword: ...
    @property
    def WALQCALC(self) -> ParserKeyword: ...
    @property
    def WAPI(self) -> ParserKeyword: ...
    @property
    def WARN(self) -> ParserKeyword: ...
    @property
    def WATDENT(self) -> ParserKeyword: ...
    @property
    def WATER(self) -> ParserKeyword: ...
    @property
    def WATJT(self) -> ParserKeyword: ...
    @property
    def WATVISCT(self) -> ParserKeyword: ...
    @property
    def WBHGLR(self) -> ParserKeyword: ...
    @property
    def WBOREVOL(self) -> ParserKeyword: ...
    @property
    def WCALCVAL(self) -> ParserKeyword: ...
    @property
    def WCONHIST(self) -> ParserKeyword: ...
    @property
    def WCONINJ(self) -> ParserKeyword: ...
    @property
    def WCONINJE(self) -> ParserKeyword: ...
    @property
    def WCONINJH(self) -> ParserKeyword: ...
    @property
    def WCONINJP(self) -> ParserKeyword: ...
    @property
    def WCONPROD(self) -> ParserKeyword: ...
    @property
    def WCUTBACK(self) -> ParserKeyword: ...
    @property
    def WCUTBACT(self) -> ParserKeyword: ...
    @property
    def WCYCLE(self) -> ParserKeyword: ...
    @property
    def WDFAC(self) -> ParserKeyword: ...
    @property
    def WDFACCOR(self) -> ParserKeyword: ...
    @property
    def WDRILPRI(self) -> ParserKeyword: ...
    @property
    def WDRILRES(self) -> ParserKeyword: ...
    @property
    def WDRILTIM(self) -> ParserKeyword: ...
    @property
    def WECON(self) -> ParserKeyword: ...
    @property
    def WECONINJ(self) -> ParserKeyword: ...
    @property
    def WECONT(self) -> ParserKeyword: ...
    @property
    def WEFAC(self) -> ParserKeyword: ...
    @property
    def WELCNTL(self) -> ParserKeyword: ...
    @property
    def WELDEBUG(self) -> ParserKeyword: ...
    @property
    def WELDRAW(self) -> ParserKeyword: ...
    @property
    def WELEVNT(self) -> ParserKeyword: ...
    @property
    def WELLDIMS(self) -> ParserKeyword: ...
    @property
    def WELLSTRE(self) -> ParserKeyword: ...
    @property
    def WELL_COMPLETION_PROBE(self) -> ParserKeyword: ...
    @property
    def WELL_PROBE(self) -> ParserKeyword: ...
    @property
    def WELL_PROBE_COMP(self) -> ParserKeyword: ...
    @property
    def WELL_PROBE_OPM(self) -> ParserKeyword: ...
    @property
    def WELMOVEL(self) -> ParserKeyword: ...
    @property
    def WELOPEN(self) -> ParserKeyword: ...
    @property
    def WELOPENL(self) -> ParserKeyword: ...
    @property
    def WELPI(self) -> ParserKeyword: ...
    @property
    def WELPRI(self) -> ParserKeyword: ...
    @property
    def WELSEGS(self) -> ParserKeyword: ...
    @property
    def WELSOMIN(self) -> ParserKeyword: ...
    @property
    def WELSPECL(self) -> ParserKeyword: ...
    @property
    def WELSPECS(self) -> ParserKeyword: ...
    @property
    def WELTARG(self) -> ParserKeyword: ...
    @property
    def WELTRAJ(self) -> ParserKeyword: ...
    @property
    def WFOAM(self) -> ParserKeyword: ...
    @property
    def WFRICSEG(self) -> ParserKeyword: ...
    @property
    def WFRICSGL(self) -> ParserKeyword: ...
    @property
    def WFRICTN(self) -> ParserKeyword: ...
    @property
    def WFRICTNL(self) -> ParserKeyword: ...
    @property
    def WGASPROD(self) -> ParserKeyword: ...
    @property
    def WGORPEN(self) -> ParserKeyword: ...
    @property
    def WGRUPCON(self) -> ParserKeyword: ...
    @property
    def WH2NUM(self) -> ParserKeyword: ...
    @property
    def WH3NUM(self) -> ParserKeyword: ...
    @property
    def WHEDREFD(self) -> ParserKeyword: ...
    @property
    def WHISTCTL(self) -> ParserKeyword: ...
    @property
    def WHTEMP(self) -> ParserKeyword: ...
    @property
    def WINJCLN(self) -> ParserKeyword: ...
    @property
    def WINJDAM(self) -> ParserKeyword: ...
    @property
    def WINJFCNC(self) -> ParserKeyword: ...
    @property
    def WINJGAS(self) -> ParserKeyword: ...
    @property
    def WINJMULT(self) -> ParserKeyword: ...
    @property
    def WINJTEMP(self) -> ParserKeyword: ...
    @property
    def WLIFT(self) -> ParserKeyword: ...
    @property
    def WLIFTOPT(self) -> ParserKeyword: ...
    @property
    def WLIMTOL(self) -> ParserKeyword: ...
    @property
    def WLIST(self) -> ParserKeyword: ...
    @property
    def WLISTARG(self) -> ParserKeyword: ...
    @property
    def WLISTNAM(self) -> ParserKeyword: ...
    @property
    def WMICP(self) -> ParserKeyword: ...
    @property
    def WNETCTRL(self) -> ParserKeyword: ...
    @property
    def WNETDP(self) -> ParserKeyword: ...
    @property
    def WORKLIM(self) -> ParserKeyword: ...
    @property
    def WORKTHP(self) -> ParserKeyword: ...
    @property
    def WPAVE(self) -> ParserKeyword: ...
    @property
    def WPAVEDEP(self) -> ParserKeyword: ...
    @property
    def WPIMULT(self) -> ParserKeyword: ...
    @property
    def WPIMULTL(self) -> ParserKeyword: ...
    @property
    def WPITAB(self) -> ParserKeyword: ...
    @property
    def WPLUG(self) -> ParserKeyword: ...
    @property
    def WPMITAB(self) -> ParserKeyword: ...
    @property
    def WPOLYMER(self) -> ParserKeyword: ...
    @property
    def WPOLYRED(self) -> ParserKeyword: ...
    @property
    def WPOTCALC(self) -> ParserKeyword: ...
    @property
    def WREGROUP(self) -> ParserKeyword: ...
    @property
    def WRFT(self) -> ParserKeyword: ...
    @property
    def WRFTPLT(self) -> ParserKeyword: ...
    @property
    def WSALT(self) -> ParserKeyword: ...
    @property
    def WSCCLEAN(self) -> ParserKeyword: ...
    @property
    def WSCCLENL(self) -> ParserKeyword: ...
    @property
    def WSCTAB(self) -> ParserKeyword: ...
    @property
    def WSEGAICD(self) -> ParserKeyword: ...
    @property
    def WSEGDFIN(self) -> ParserKeyword: ...
    @property
    def WSEGDFMD(self) -> ParserKeyword: ...
    @property
    def WSEGDFPA(self) -> ParserKeyword: ...
    @property
    def WSEGDIMS(self) -> ParserKeyword: ...
    @property
    def WSEGEXSS(self) -> ParserKeyword: ...
    @property
    def WSEGFLIM(self) -> ParserKeyword: ...
    @property
    def WSEGFMOD(self) -> ParserKeyword: ...
    @property
    def WSEGINIT(self) -> ParserKeyword: ...
    @property
    def WSEGITER(self) -> ParserKeyword: ...
    @property
    def WSEGLABY(self) -> ParserKeyword: ...
    @property
    def WSEGLINK(self) -> ParserKeyword: ...
    @property
    def WSEGMULT(self) -> ParserKeyword: ...
    @property
    def WSEGPROP(self) -> ParserKeyword: ...
    @property
    def WSEGSEP(self) -> ParserKeyword: ...
    @property
    def WSEGSICD(self) -> ParserKeyword: ...
    @property
    def WSEGSOLV(self) -> ParserKeyword: ...
    @property
    def WSEGTABL(self) -> ParserKeyword: ...
    @property
    def WSEGVALV(self) -> ParserKeyword: ...
    @property
    def WSF(self) -> ParserKeyword: ...
    @property
    def WSKPTAB(self) -> ParserKeyword: ...
    @property
    def WSOLVENT(self) -> ParserKeyword: ...
    @property
    def WSURFACT(self) -> ParserKeyword: ...
    @property
    def WTADD(self) -> ParserKeyword: ...
    @property
    def WTEMP(self) -> ParserKeyword: ...
    @property
    def WTEMPQ(self) -> ParserKeyword: ...
    @property
    def WTEST(self) -> ParserKeyword: ...
    @property
    def WTHPMAX(self) -> ParserKeyword: ...
    @property
    def WTMULT(self) -> ParserKeyword: ...
    @property
    def WTRACER(self) -> ParserKeyword: ...
    @property
    def WVFPDP(self) -> ParserKeyword: ...
    @property
    def WVFPEXP(self) -> ParserKeyword: ...
    @property
    def WWPAVE(self) -> ParserKeyword: ...
    @property
    def XMF(self) -> ParserKeyword: ...
    @property
    def YMF(self) -> ParserKeyword: ...
    @property
    def YMODULE(self) -> ParserKeyword: ...
    @property
    def ZCORN(self) -> ParserKeyword: ...
    @property
    def ZFACT1(self) -> ParserKeyword: ...
    @property
    def ZFACT1S(self) -> ParserKeyword: ...
    @property
    def ZFACTOR(self) -> ParserKeyword: ...
    @property
    def ZFACTORS(self) -> ParserKeyword: ...
    @property
    def ZIPP2OFF(self) -> ParserKeyword: ...
    @property
    def ZIPPY2(self) -> ParserKeyword: ...
    @property
    def ZMFVD(self) -> ParserKeyword: ...

class Connection:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def attached_to_segment(self) -> bool: ...
    @property
    def center_depth(self) -> float: ...
    @property
    def cf(self) -> float: ...
    @property
    def complnum(self) -> int: ...
    @property
    def direction(self) -> str: ...
    @property
    def i(self) -> int: ...
    @property
    def j(self) -> int: ...
    @property
    def k(self) -> int: ...
    @property
    def kh(self) -> float: ...
    @property
    def number(self) -> int: ...
    @property
    def pos(self) -> Tuple[int, int, int]: ...
    @property
    def rw(self) -> float: ...
    @property
    def sat_table_id(self) -> int: ...
    @property
    def segment_number(self) -> int: ...
    @property
    def state(self) -> str: ...

class Deck:
    def __init__(self, *args, **kwargs) -> None: ...
    def active_unit_system(self, *args, **kwargs): ...
    def add(self, arg0) -> None: ...
    def count(self, arg0: str) -> int: ...
    def default_unit_system(self, *args, **kwargs): ...
    def __contains__(self, arg0: str) -> bool: ...
    def __getitem__(self, index): ...
    def __iter__(self) -> Iterator: ...
    def __len__(self) -> int: ...

class DeckItem:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_SI(self, arg0: int) -> float: ...
    def get_SI_data_list(self) -> list: ...
    def get_data_list(self) -> list: ...
    def get_int(self, arg0: int) -> int: ...
    def get_raw(self, arg0: int) -> float: ...
    def get_raw_data_list(self) -> list: ...
    def get_str(self, arg0: int) -> str: ...
    def get_uda(self, *args, **kwargs): ...
    def is_double(self) -> bool: ...
    def is_int(self) -> bool: ...
    def is_string(self) -> bool: ...
    def is_uda(self) -> bool: ...
    def name(self) -> str: ...
    def __len__(self) -> int: ...

class DeckKeyword:
    @overload
    def __init__(self, arg0: ParserKeyword) -> None: ...
    @overload
    def __init__(self, arg0: ParserKeyword, arg1: list, arg2, arg3) -> None: ...
    @overload
    def __init__(self, arg0: ParserKeyword, arg1: numpy.ndarray[numpy.int32]) -> None: ...
    @overload
    def __init__(self, arg0: ParserKeyword, arg1: numpy.ndarray[numpy.float64], arg2, arg3) -> None: ...
    def get_SI_array(self) -> numpy.ndarray[numpy.float64]: ...
    def get_int_array(self) -> numpy.ndarray[numpy.int32]: ...
    def get_raw_array(self) -> numpy.ndarray[numpy.float64]: ...
    def __getitem__(self, index): ...
    def __iter__(self) -> Iterator: ...
    def __len__(self) -> int: ...
    @property
    def name(self) -> str: ...

class DeckRecord:
    def __init__(self, *args, **kwargs) -> None: ...
    def __getitem__(self, index): ...
    def __iter__(self) -> Iterator: ...
    def __len__(self) -> int: ...

class Dimension:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def offset(self) -> float: ...
    @property
    def scaling(self) -> float: ...

class EGrid:
    def __init__(self, arg0: str) -> None: ...
    def active_index(self, arg0: int, arg1: int, arg2: int) -> int: ...
    @overload
    def cellvolumes(self) -> numpy.ndarray: ...
    @overload
    def cellvolumes(self, arg0: List[int]) -> numpy.ndarray: ...
    def global_index(self, arg0: int, arg1: int, arg2: int) -> int: ...
    def ijk_from_active_index(self, arg0: int) -> List[int[3]]: ...
    def ijk_from_global_index(self, arg0: int) -> List[int[3]]: ...
    def xyz_from_active_index(self, arg0: int) -> Tuple[List[float[8]], List[float[8]], List[float[8]]]: ...
    def xyz_from_ijk(self, arg0: int, arg1: int, arg2: int) -> Tuple[List[float[8]], List[float[8]], List[float[8]]]: ...
    @property
    def active_cells(self) -> int: ...
    @property
    def dimension(self) -> List[int[3]]: ...

class EModel:
    def __init__(self, arg0: str) -> None: ...
    def active_cells(self) -> int: ...
    def active_report_step(self) -> int: ...
    def add_hc_filter(self) -> None: ...
    def get(self, arg0: str) -> numpy.ndarray: ...
    def get_list_of_arrays(self) -> List[Tuple[str, eclArrType]]: ...
    def get_report_steps(self) -> List[int]: ...
    def grid_dims(self) -> Tuple[int, int, int]: ...
    def has_report_step(self, arg0: int) -> bool: ...
    def reset_filter(self) -> None: ...
    def set_depth_fwl(self, arg0: List[float]) -> None: ...
    def set_report_step(self, arg0: int) -> None: ...
    def __contains__(self, arg0: str) -> bool: ...

class ERft:
    def __init__(self, arg0: str) -> None: ...
    def __len__(self) -> int: ...
    @property
    def list_of_rfts(self) -> List[Tuple[str, Tuple[int, int, int], float]]: ...

class ERst:
    def __init__(self, arg0: str) -> None: ...
    @overload
    def arrays(self, arg0: int) -> List[Tuple[str, eclArrType, int]]: ...
    @overload
    def arrays(self, arg0: int, arg1: str) -> List[Tuple[str, eclArrType, int]]: ...
    def count(self, arg0: str, arg1: int) -> int: ...
    def load_report_step(self, arg0: int) -> None: ...
    def __len__(self) -> int: ...
    @property
    def report_steps(self) -> List[int]: ...

class ESmry:
    def __init__(self, filename: str, load_base_run: bool = ...) -> None: ...
    @overload
    def keys(self) -> List[str]: ...
    @overload
    def keys(self, arg0: str) -> List[str]: ...
    def make_esmry_file(self) -> None: ...
    def __contains__(self, arg0: str) -> bool: ...
    def __len__(self) -> int: ...
    @property
    def start_date(self) -> datetime.datetime: ...

class EclFile:
    def __init__(self, filename: str, preload: bool = ...) -> None: ...
    def count(self, arg0: str) -> int: ...
    def __contains__(self, arg0: str) -> bool: ...
    def __len__(self) -> int: ...
    @property
    def arrays(self) -> List[Tuple[str, eclArrType, int]]: ...

class EclOutput:
    def __init__(self, filename: str, formatted: bool = ..., append: bool = ...) -> None: ...
    def write_message(self, arg0: str) -> None: ...

class EclipseConfig:
    def __init__(self, *args, **kwargs) -> None: ...
    def init(self, *args, **kwargs): ...

class EclipseGrid:
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def getCellDepth(self, arg0: int) -> float: ...
    @overload
    def getCellDepth(self, arg0: int, arg1: int, arg2: int) -> float: ...
    @overload
    def getCellDepth(self) -> numpy.ndarray: ...
    @overload
    def getCellDepth(self, arg0: List[int]) -> numpy.ndarray: ...
    @overload
    def getCellVolume(self, arg0: int) -> float: ...
    @overload
    def getCellVolume(self, arg0: int, arg1: int, arg2: int) -> float: ...
    @overload
    def getCellVolume(self) -> numpy.ndarray: ...
    @overload
    def getCellVolume(self, arg0: List[int]) -> numpy.ndarray: ...
    def getIJK(self, arg0: int) -> tuple: ...
    def globalIndex(self, arg0: int, arg1: int, arg2: int) -> int: ...
    @property
    def cartesianSize(self) -> int: ...
    @property
    def nactive(self) -> int: ...
    @property
    def nx(self) -> int: ...
    @property
    def ny(self) -> int: ...
    @property
    def nz(self) -> int: ...

class EclipseState:
    def __init__(self, arg0: Deck) -> None: ...
    def config(self) -> EclipseConfig: ...
    def faultFaces(self, arg0: str) -> list: ...
    def faultNames(self) -> list: ...
    def field_props(self) -> FieldProperties: ...
    def grid(self, *args, **kwargs): ...
    def has_input_nnc(self) -> bool: ...
    def input_nnc(self) -> list: ...
    def jfunc(self) -> dict: ...
    def simulation(self) -> SimulationConfig: ...
    def tables(self, *args, **kwargs): ...
    @property
    def title(self) -> str: ...

class FieldProperties:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_double_array(self, arg0: str) -> numpy.ndarray[numpy.float64]: ...
    def get_int_array(self, arg0: str) -> numpy.ndarray[numpy.int32]: ...
    def __contains__(self, arg0: str) -> bool: ...
    def __getitem__(self, arg0: str) -> numpy.ndarray: ...

class Group:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def num_wells(self) -> int: ...
    @property
    def well_names(self) -> List[str]: ...

class IOConfig:
    def __init__(self, *args, **kwargs) -> None: ...

class InitConfig:
    def __init__(self, *args, **kwargs) -> None: ...
    def getRestartStep(self) -> int: ...
    def hasEquil(self) -> bool: ...
    def restartRequested(self) -> bool: ...

class OpmLog:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def bug(arg0: str) -> None: ...
    @staticmethod
    def debug(arg0: str) -> None: ...
    @staticmethod
    def error(arg0: str) -> None: ...
    @staticmethod
    def info(arg0: str) -> None: ...
    @staticmethod
    def note(arg0: str) -> None: ...
    @staticmethod
    def problem(arg0: str) -> None: ...
    @staticmethod
    def warning(arg0: str) -> None: ...

class ParseContext:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0) -> None: ...
    def ignore_keyword(self, arg0: str) -> None: ...
    def update(self, arg0: str, arg1) -> None: ...

class Parser:
    def __init__(self, add_default: bool = ...) -> None: ...
    @overload
    def add_keyword(self, arg0: ParserKeyword) -> None: ...
    @overload
    def add_keyword(self, arg0: str) -> None: ...
    def parse(self, *args, **kwargs): ...
    def parse_string(self, *args, **kwargs): ...
    def __getitem__(self, arg0: str) -> ParserKeyword: ...

class ParserKeyword:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def name(self) -> str: ...

class Schedule:
    def __init__(self, arg0: Deck, arg1) -> None: ...
    def get_injection_properties(self, well_name: str, report_step: int) -> Dict[str, float]: ...
    def get_production_properties(self, well_name: str, report_step: int) -> Dict[str, float]: ...
    def get_well(self, *args, **kwargs): ...
    def get_wells(self, *args, **kwargs): ...
    @overload
    def insert_keywords(self, keywords: list, step: int) -> None: ...
    @overload
    def insert_keywords(self, data: str, step: int, unit_system) -> None: ...
    @overload
    def insert_keywords(self, data: str, step: int) -> None: ...
    @overload
    def insert_keywords(self, data: str) -> None: ...
    @overload
    def open_well(self, well_name: str, step: int) -> None: ...
    @overload
    def open_well(self, well_name: str) -> None: ...
    @overload
    def shut_well(self, well_name: str, step: int) -> None: ...
    @overload
    def shut_well(self, well_name: str) -> None: ...
    @overload
    def stop_well(self, well_name: str, step: int) -> None: ...
    @overload
    def stop_well(self, well_name: str) -> None: ...
    def well_names(self, arg0: str) -> List[str]: ...
    def __contains__(self, arg0: str) -> bool: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    @property
    def end(self) -> datetime.datetime: ...
    @property
    def start(self) -> datetime.datetime: ...
    @property
    def timesteps(self) -> List[datetime.datetime]: ...

class ScheduleState:
    def __init__(self, *args, **kwargs) -> None: ...
    def group(self, *args, **kwargs): ...
    @property
    def nupcol(self) -> int: ...

class SimulationConfig:
    def __init__(self, *args, **kwargs) -> None: ...
    def hasDISGAS(self) -> bool: ...
    def hasDISGASW(self) -> bool: ...
    def hasThresholdPressure(self) -> bool: ...
    def hasVAPOIL(self) -> bool: ...
    def hasVAPWAT(self) -> bool: ...
    def useCPR(self) -> bool: ...
    def useNONNC(self) -> bool: ...

class SummaryConfig:
    def __init__(self, arg0: Deck, arg1, arg2: Schedule) -> None: ...
    def __contains__(self, arg0: str) -> bool: ...

class SummaryState:
    def __init__(self, arg0: int) -> None: ...
    def elapsed(self) -> float: ...
    def group_var(self, arg0: str, arg1: str) -> float: ...
    def has_group_var(self, arg0: str, arg1: str) -> bool: ...
    def has_well_var(self, arg0: str, arg1: str) -> bool: ...
    def update(self, arg0: str, arg1: float) -> None: ...
    def update_group_var(self, arg0: str, arg1: str, arg2: float) -> None: ...
    def update_well_var(self, arg0: str, arg1: str, arg2: float) -> None: ...
    def well_var(self, arg0: str, arg1: str) -> float: ...
    def __contains__(self, arg0: str) -> bool: ...
    def __getitem__(self, arg0: str) -> float: ...
    def __setitem__(self, arg0: str, arg1: float) -> None: ...
    @property
    def groups(self) -> List[str]: ...
    @property
    def wells(self) -> List[str]: ...

class Tables:
    def __init__(self, *args, **kwargs) -> None: ...
    def evaluate(self, arg0: str, arg1: int, arg2: str, arg3: float) -> float: ...
    def __contains__(self, arg0: str) -> bool: ...

class UDAValue:
    @overload
    def __init__(self, arg0: float, arg1) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1) -> None: ...
    def dimension(self, *args, **kwargs): ...
    def get_double(self) -> float: ...
    def get_string(self) -> str: ...
    def is_double(self) -> bool: ...
    def is_string(self) -> bool: ...

class UnitSystem:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def name(self) -> str: ...

class Well:
    def __init__(self, *args, **kwargs) -> None: ...
    def available_gctrl(self) -> bool: ...
    def connections(self, *args, **kwargs): ...
    def group(self) -> str: ...
    def guide_rate(self) -> float: ...
    def isdefined(self, arg0: int) -> bool: ...
    def isinjector(self) -> bool: ...
    def isproducer(self) -> bool: ...
    def pos(self) -> Tuple[int, int, float]: ...
    def status(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def preferred_phase(self) -> str: ...

class action:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    ignore: ClassVar[action] = ...
    throw: ClassVar[action] = ...
    warn: ClassVar[action] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class eclArrType:
    __members__: ClassVar[dict] = ...  # read-only
    C0nn: ClassVar[eclArrType] = ...
    CHAR: ClassVar[eclArrType] = ...
    DOUB: ClassVar[eclArrType] = ...
    INTE: ClassVar[eclArrType] = ...
    LOGI: ClassVar[eclArrType] = ...
    MESS: ClassVar[eclArrType] = ...
    REAL: ClassVar[eclArrType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class eclSectionType:
    __members__: ClassVar[dict] = ...  # read-only
    EDIT: ClassVar[eclSectionType] = ...
    GRID: ClassVar[eclSectionType] = ...
    PROPS: ClassVar[eclSectionType] = ...
    REGIONS: ClassVar[eclSectionType] = ...
    RUNSPEC: ClassVar[eclSectionType] = ...
    SCHEDULE: ClassVar[eclSectionType] = ...
    SOLUTION: ClassVar[eclSectionType] = ...
    SUMMARY: ClassVar[eclSectionType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __and__(self, other: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> object: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other: object) -> object: ...
    def __rand__(self, other: object) -> object: ...
    def __ror__(self, other: object) -> object: ...
    def __rxor__(self, other: object) -> object: ...
    def __xor__(self, other: object) -> object: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

def calc_cell_vol(arg0: List[float[8]], arg1: List[float[8]], arg2: List[float[8]]) -> float: ...
def create_deck(*args, **kwargs): ...
def create_deck_string(*args, **kwargs): ...
