macro(opm_add_dependencies)
  cmake_parse_arguments(PARAM "" "PREFIX" "REQUIRED;OPTIONAL" ${ARGN})
  if(NOT PARAM_PREFIX)
    message(FATAL_ERROR "Macro needs a PREFIX parameter")
  endif()
  if(${PARAM_PREFIX}_TARGET)
    return()
  endif()
  set(${PARAM_PREFIX}_LIBRARIES)
  foreach(dep ${PARAM_REQUIRED})
    list(APPEND ${PARAM_PREFIX}_LIBRARIES ${dep})
  endforeach()
  foreach(dep ${PARAM_OPTIONAL})
    if(TARGET ${dep})
      list(APPEND ${PARAM_PREFIX}_LIBRARIES ${dep})
    endif()
  endforeach()
endmacro()
