# Help HDF5 usage on rhel
if(NOT DEFINED ENV{HDF5_ROOT} AND NOT HDF5_ROOT AND DEFINED ENV{MPI_INCLUDE} AND DEFINED ENV{MPI_LIB})
  set(HDF5_ROOT $ENV{MPI_LIB})
  set(HDF5_INCLUDE_DIR $ENV{MPI_INCLUDE})
  set(HDF5_C_INCLUDE_DIR $ENV{MPI_INCLUDE})
endif()

if(USE_MPI)
  set(HDF5_PREFER_PARALLEL ON)
endif()
